# Generated by Django 2.2.5 on 2020-11-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='CP_state',
            field=models.IntegerField(default=2),
        ),
    ]
