# Generated by Django 2.2.5 on 2020-11-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20201109_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_con',
            field=models.IntegerField(default=0),
        ),
    ]
