# Generated by Django 2.2.5 on 2020-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20201122_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='CP_validity',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
