# Generated by Django 2.2.5 on 2020-11-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20201122_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='CP_date',
            field=models.DateTimeField(null=True),
        ),
    ]
