# Generated by Django 2.2.5 on 2020-11-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_dongseopay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AlterField(
            model_name='dongseopay',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AlterField(
            model_name='shippingdestination',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
        migrations.AlterField(
            model_name='shoppingbasket',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.User'),
        ),
    ]
