# Generated by Django 2.2.5 on 2020-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20201122_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongseopay',
            name='DP_TradingDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
