# Generated by Django 2.2.5 on 2020-11-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20201112_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_con',
            field=models.IntegerField(default=0),
        ),
    ]
