# Generated by Django 2.2.5 on 2020-11-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20201110_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='CP_Used',
            new_name='CP_received',
        ),
    ]
