# Generated by Django 2.2.5 on 2020-11-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20201122_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_reserves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Reserves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='User_Reserves',
            field=models.IntegerField(default=0),
        ),
    ]
