# Generated by Django 2.2.5 on 2020-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_order_order_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksb',
            name='BookSB_type',
            field=models.BooleanField(default=1),
        ),
    ]
