# Generated by Django 2.2.5 on 2020-11-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20201124_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_reserves',
        ),
        migrations.AddField(
            model_name='booksb',
            name='BookSB_reserves',
            field=models.IntegerField(default=0),
        ),
    ]
