# Generated by Django 2.2.5 on 2020-11-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_booksb_booksb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Order'),
        ),
    ]
