# Generated by Django 2.2.5 on 2020-11-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20201113_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_con',
            field=models.BooleanField(default=0),
        ),
    ]
