# Generated by Django 2.2.5 on 2020-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_auto_20201113_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_DC_totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
