# Generated by Django 2.2.5 on 2020-11-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_book_booksb_reserves'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='BO_reserves',
            field=models.IntegerField(default=0),
        ),
    ]
