# Generated by Django 2.2.5 on 2020-11-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_order_order_dc_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='CP_Used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='CP_state',
            field=models.IntegerField(default=0),
        ),
    ]
