# Generated by Django 2.2.5 on 2020-11-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_bookorder_bo_reserves'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_used_Reserves',
            field=models.IntegerField(default=0),
        ),
    ]
