# Generated by Django 2.2.5 on 2020-11-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20201116_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dongseopay',
            name='DP_TradingDate',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
