# Generated by Django 2.2.5 on 2020-11-24 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_order_order_used_reserves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookSB_reserves',
            new_name='Book_reserves',
        ),
    ]
