# Generated by Django 2.2.5 on 2020-11-20 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_auto_20201120_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Select_Card_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Select_SD_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dongseopay',
            name='DP_TradingDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
