# Generated by Django 2.2.5 on 2020-11-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20201102_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP_kind', models.CharField(max_length=100)),
                ('CP_Used', models.BooleanField(default=0)),
                ('CP_date', models.DateTimeField()),
                ('CP_validity', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.User')),
            ],
        ),
    ]
