# Generated by Django 2.2.5 on 2020-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='BO_DC_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='CP_kind',
            field=models.CharField(default='', max_length=100),
        ),
    ]
