# Generated by Django 2.2.5 on 2020-11-09 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookorder',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bookstore.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
