# Generated by Django 2.2.5 on 2020-11-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
